export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET'

export const DETAIL_ORDER_REQUEST = 'DETAIL_ORDER_REQUEST'
export const DETAIL_ORDER_SUCCESS = 'DETAIL_ORDER_SUCCESS'
export const DETAIL_ORDER_FAILURE = 'DETAIL_ORDER_FAILURE'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE = 'ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAILURE = 'ORDER_LIST_FAILURE'